export const dropdownOptions = [
    "-",
    "Cross-site Scripting (XSS)",
    "Prototype Pollution",
    "SQL Injection",
    "Buffer Overflow",
    "Command Injection",
    "Code Injection",
    "Path Traversal",
    "Directory Traversal",
    "Remote File Inclusion",
    "Local File Inclusion",
    "Security Misconfiguration",
    "Insecure Direct Object References",
    "Missing Function Level Access Control",
    "Cross-Site Request Forgery (CSRF)",
    "Unvalidated Redirects and Forwards",
    "Server-side Request Forgery (SSRF)",
    "Denial-of-service (DoS)",
    "Distributed Denial-of-service (DDoS)",
    "Unrestricted Upload of File with Dangerous Type",
    "Use of Hard-coded Password",
    "XML External Entity (XXE)",
    "Improper Limitation of a Pathname to a Restricted Directory",
    "Heap-based Buffer Overflow",
    "Stack-based Buffer Overflow",
    "Improper Handling of Length Parameter Inconsistency",
    "Improper Control of Generation of Code",
    "Integer Overflow or Wraparound",
    "Out-of-bounds Write",
    "Improper Neutralization of Special Elements used in an SQL Command",
    "Injection",
    "Path Traversal",
    "Cross-origin Resource Sharing",
    "Inclusion of Functionality from Untrusted Control Sphere",
    "Uncontrolled Resource Consumption",
    "Untrusted Search Path",
    "Use After Free",
    "Improper Privilege Management",
    "Race Condition",
    "Insufficiently Protected Credentials",
    "Use of a Broken or Risky Cryptographic Algorithm",
    "Missing Encryption of Sensitive Data",
    "Improper Restriction of Excessive Authentication Attempts",
    "Improper Restriction of Operations within the Bounds of a Memory Buffer",
    "Improper Initialization",
    "Null Pointer Dereference",
    "Infinite Loop",
    "Incorrect Type Conversion or Cast",
    "Improper Resource Shutdown or Release",
    "Improper Verification of Cryptographic Signature",
    "Improper Check for Unusual or Exceptional Conditions",
    "Missing Release of Resource after Effective Lifetime",
    "Integer Underflow (Wrap or Wraparound)",
    "Improper Restriction of XML External Entity Reference",
    "Out-of-bounds Read",
    "Improper Verification of Integrity Check Value",
    "Uncontrolled Format String",
    "Improper Use of Regular Expression",
    "Relative Path Traversal",
    "Failure to Constrain Operations within the Bounds of a Memory Buffer",
    "Improperly Implemented Security Check for Standard",
    "Exposure of Sensitive Information to an Unauthorized Actor",
    "Missing Authentication for Critical Function",
    "Information Exposure Through an Error Message",
    "Insufficiently Protected Credentials",
    "Insecure Storage of Sensitive Information",
    "Inadequate Encryption Strength",
    "Weak Password Requirements",
    "Missing Password Change Function",
    "Insufficient Process Isolation",
    "Improper Access Control",
    "Insecure Default Configuration",
    "Failure to Protect Stored Data from Modification",
    "Execution with Unnecessary Privileges",
    "Unnecessary Exposure of Information",
    "Failure to Provide Privacy Notice",
    "Insufficiently Protected Backup",
    "Missing Security Headers",
    "Unprotected Transport of Credentials",
    "Improper Certificate Validation",
    "Weak Password Recovery Mechanism for Forgotten Password",
    "Failure to Handle Missing or Unexpected Data",
    "Failure to Drop Privileges",
    "Untrusted Initialization",
    "Download of Code Without Integrity Check",
    "Incorrect Permission Assignment for Critical Resource",
    "Incorrect Default Permissions",
    "Missing Authorization",
    "Missing Encryption of Sensitive Data",
    "Use of Insufficiently Random Values",
    "Insufficient Verification of Data Authenticity",
    "Insufficiently Protected Credentials",
    "Incorrect Behavior Order: Early Amplification",
    "Incorrect Behavior Order: Validate Before Canonicalize",
    "Missing Protection Mechanism",
    "Insufficient Session Expiration",
    "Incorrect Permission Assignment for Critical Resource",
    "Inclusion of Sensitive Information in Log Files",
    "Improper Validation of Array Index",
    "Improper Check for Dropped Privileges",
    "Improper Validation of SSL/TLS Certificates",
    "Insufficient Entropy",
    "Improper Control of a Resource Through its Lifetime",
    "Failure to Provide Confidentiality",
    "Exposure of Resource to Wrong Sphere",
    "Inclusion of Functionality from Untrusted Control Sphere",
    "Improper Limitation of a Pathname to a Restricted Directory",
    "Creation of Temporary File With Insecure Permissions",
    "Use of Potentially Dangerous Function",
    "Failure to Preserve Web Page Structure",
    "Improper Sanitization of HTML Tags",
    "Improper Enforcement of Message or Data Structure",
    "Improper Verification of a Cryptographic Signature",
    "Failure to Encrypt Sensitive Traffic",
    "Storing Passwords in a Recoverable Format",
    "Missing Authentication for Critical Function",
    "Cross-Frame Scripting (XFS)",
    "Improperly Controlled Modification of Dynamically-Determined Object Attributes",
    "Inadequate Encryption Strength",
    "Insufficiently Protected Backup",
    "Password in Configuration File",
    "Race Conditions",
    "Lack of User Control Over Privacy Settings",
    "Lack of Necessary Functionality in a Security Mechanism",
];
